import { config } from "@resfolio/eslint-config/base";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...config,
  {
    // src/schema/auth.ts is generated by the Better Auth CLI
    // (docs/architecture/10-auth-and-security.md) — never hand-edited,
    // so never hand-linted.
    ignores: ["src/schema/auth.ts", "migrations/**"],
  },
];
