import { relations } from "drizzle-orm";
import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import { profile } from "./profiles";

/**
 * Resfolio AI chat sessions — saved transcripts
 * (docs/architecture/13-ai-layer.md, 07-storage.md).
 *
 * **A row here is a record of what was said, never an input to what happens
 * next.** The model's context is still built per request from the Profile and
 * the turns the client posts (`lib/ai/chat-request.ts`); nothing reads this
 * table on the way to a provider. That is what keeps persistence from quietly
 * becoming memory: a saved transcript that fed the next prompt would be a second
 * source of truth about the user's career, sitting beside the Profile and
 * disagreeing with it.
 *
 * **Profile-owned, like every other content table**, so deleting a profile takes
 * its chat history with it in one cascade rather than in a cleanup nobody
 * remembers to write. It is scoped to the profile rather than the user for the
 * same reason `blog_posts` is: the Profile is what the conversation was about.
 *
 * `messages` is the SDK's `UIMessage[]` as stored by `@resfolio/ai`, minus
 * reasoning parts (dropped before the write — doc 13 renders no
 * chain-of-thought, and storing it would be a stronger commitment than
 * rendering it). JSONB rather than a `messages` table because a transcript is
 * only ever read and written whole: there is no query that wants one turn, and
 * a row per part would buy nothing but joins.
 *
 * `message_count` is denormalised so the history rail can list fifty sessions
 * without loading fifty transcripts — the same reason `blog_posts` stores
 * `reading_minutes`. It is written only from the array beside it.
 */
export const aiChatSession = pgTable(
  "ai_chat_sessions",
  {
    /** Client-generated (a UUID minted when the chat starts), so the first save
     * of a new conversation is an upsert rather than a create-then-adopt — which
     * is what lets the transcript be saved without the composer ever waiting on
     * a round trip for its own id. */
    id: uuid("id").primaryKey(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => profile.id, { onDelete: "cascade" }),

    /** Derived from the first user message (`deriveSessionTitle`), not asked for
     * and not generated by a model. */
    title: text("title").notNull(),

    /** `StoredChatMessage[]`, validated by `@resfolio/ai` on the way in *and*
     * out — a transcript written before a schema change should fail here rather
     * than reach the chat as a message it cannot render. */
    messages: jsonb("messages").notNull().default([]),

    messageCount: integer("message_count").notNull().default(0),

    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    // The history rail's only query: this profile's sessions, newest activity
    // first. Composite rather than two indexes — the sort is never done without
    // the filter.
    index("ai_chat_sessions_profile_updated_idx").on(
      table.profileId,
      table.updatedAt.desc(),
    ),
  ],
);

export const aiChatSessionRelations = relations(aiChatSession, ({ one }) => ({
  profile: one(profile, {
    fields: [aiChatSession.profileId],
    references: [profile.id],
  }),
}));
