/**
 * Drizzle schema, one module per concern.
 *
 * `./auth` is generated by the Better Auth CLI (`pnpm --filter
 * @resfolio/auth db:generate-schema`) and committed — never hand-edited
 * (docs/architecture/10-auth-and-security.md). Product tables land with
 * their features (docs/architecture/07-storage.md): `./profiles` in
 * Phase 3; `./documents` in Phase 4; `./sites` in Phase 5; `./integrations`
 * in Phase 6; `./assets` with R2 uploads.
 */
export * from "./auth";
export * from "./profiles";
export * from "./documents";
export * from "./sites";
export * from "./integrations";
export * from "./assets";
