/**
 * Drizzle schema, one module per concern.
 *
 * `./auth` is generated by the Better Auth CLI (`pnpm --filter
 * @resfolio/auth db:generate-schema`) and committed — never hand-edited
 * (docs/architecture/10-auth-and-security.md). Product tables (profiles,
 * documents, sites, …) land with their features in later phases
 * (docs/architecture/07-storage.md).
 */
export * from "./auth";
