/**
 * Drizzle schema, one module per concern.
 *
 * `./auth` is generated by the Better Auth CLI (`pnpm --filter
 * @resfolio/auth db:generate-schema`) and committed — never hand-edited
 * (docs/architecture/10-auth-and-security.md). Product tables land with
 * their features (docs/architecture/07-storage.md): `./profiles` in
 * Phase 3; `documents`, `sites`, `assets` in later phases.
 */
export * from "./auth";
export * from "./profiles";
